GET http://localhost/projetPhp/public/api/users

###

GET http://localhost/projetPhp/public/api/user/1

###

GET http://localhost/projetPhp/public/api/carte

###


POST http://localhost/projetPhp/public/api/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "123456789"
}

###

POST http://localhost/projetPhp/public/api/register
content-type: application/json

{
    "email": "test3t@test.com",
    "password": "123456789",
    "name": "test3",
    "prenom": "test3Prenom",
    "age": 23,
    "sexe": "F",
    "adresse": "G5",
    "telephone": 6872569852,
    "ville": "Rabat"
}

###

POST http://localhost/projetPhp/public/api/formulaire
content-type: application/json

{
    "user_id": 2,
    "test": 3,
    "isolement": 3,
    "situations": "",
    "symptomes": "",
    "toux": 3
}


