GET http://localhost/projetPhp/public/api/users

###

GET http://localhost/projetPhp/public/api/user/3

###

GET http://localhost/projetPhp/public/api/carte

###


POST http://localhost/projetPhp/public/api/login
content-type: application/json

{
    "email": "test1t@test.com",
    "password": "123456789"
}

###

POST http://localhost/projetPhp/public/api/register
content-type: application/json

{
    "email": "test5@test.com",
    "password": "123456789",
    "name": "test5",
    "prenom": "test5Prenom",
    "age": 30,
    "sexe": "M",
    "adresse": "mesnana",
    "telephone": 6872569852,
    "ville": "Tanger"
}

###

POST http://localhost/projetPhp/public/api/formulaire
content-type: application/json

{
    "user_id": 1,
    "test": 3,
    "isolement": 3,
    "situations": "",
    "symptomes": "",
    "toux": 3
}


